### PR TITLE
🛠  UI fixes and code cleaning

### PR DESCRIPTION
**Pull request by MedRedha**
## Motivation

First of all, I wanted to express to you my pride towards the tremendous efforts you made achieving a surprising UI implementation and coding level. I know it's probably nothing, but I took some time reading, analyzing and wanted to contribute to your code to push you up and forward 🚀  Never give up! 

#InCodeWeTrust

_PS: I've also noticed some **GitiMoji** commit 👌_ 

## Description

- Added new fading animations for the title and description ✨ .
- Added new dropping animation to the mobile background 🤩 .
- Passed the vacuum cleaner over some duplicated code 🧼 .

## Screenshots

image

### CODE REVIEW

**Comment by zineb-Bou** [comment]
Hey Redha,
Thank you for taking the time to read and analyze my code, it is very helpful for me to get such a review, I am an entry-level, still, need to learn more. 
Again I deeply appreciate your contribution 😊.

**Comment by MedRedha** [comment]
> Hey Redha,
> Thank you for taking the time to read and analyze my code, it is very helpful for me to get such a review, I am an entry-level, still, need to learn more.
> Again I deeply appreciate your contribution 😊.

With pure pleasure 🙇‍♂️  I'm constantly monitoring/following your journey 😇  

Very proud of you!

**Comment by zineb-Bou** [comment]
You have been always an inspiration and the one who got me to love what I am doing 🙏.

**Comment by MedRedha** [comment]
> You have been always an inspiration and the one who got me to love what I am doing 🙏.

It's the most beautiful thing I've never heard 🙇‍♂️  I always believed in you and gave everything so you can find your passion and live it!

If you need anything ; from sharing, collaborating, asking questions to any `variable`, you still an owner on [Nebula Team](https://github.com/Nebula-Team) and I'll be more than honored 🙏 

Very proud of you!

**Pull request merged**
